### PR TITLE
Small ctrl c ctrl v fix

### PR DESCRIPTION
**Pull request by freeshitcoder**
Signed-off-by: freeshitcoder <125373277+freeshitcoder@users.noreply.github.com>
I'm dumb so I can do pull request wrong 

ctrl c ctrl v from whatevergreeen

### CODE REVIEW

**Comment by ChefKissInc** [comment]
This Kext does not conflict with WhateverGreen. You're supposed to use it in combination.

**Comment by SsNiPeR1** [comment]
@ChefKissInc lmao what

**Comment by Hepi34** [comment]
@freeshitcoder This kext is not a copy bruh

**Comment by freeshitcoder** [comment]
@Hepi34 I know the code can be cut out;)))))

**Comment by ChefKissInc** [comment]
@freeshitcoder This would cause licensing issues. Our license is not compatible and will not be compatible with any projects from Acidanthera and others. This license is specifically made so people cannot profit from the kext, i.e. by selling EFIs.

**Comment by freeshitcoder** [comment]
I thought about it, but I live in Russia, we can ;)

**Comment by ChefKissInc** [comment]
K

**Pull request closed without merging**
